namespace EmotePurge.Core.Entities;

// The vocabulary of EmoteTagOperation.Kind.
public static class EmoteTagOperationKind
{
    public const string PlayIn = "playIn";
    public const string Removal = "removal";

    /// <summary>Whether <paramref name="kind"/> is one of the two values, compared ordinally.</summary>
    public static bool IsKnown(string? kind) =>
        string.Equals(kind, PlayIn, StringComparison.Ordinal) || string.Equals(kind, Removal, StringComparison.Ordinal);
}

/// <summary>
/// A play-in or removal run, registered by the browser before it touches 7TV. The server stamps
/// <see cref="RegisteredAtUtc"/> from its own clock; that instant is what a leave observation is
/// compared against, which is why registration must come first. A report is only accepted for a
/// registered operation of the same set that has not been applied yet.
/// </summary>
public class EmoteTagOperation
{
    /// <summary>Generated by the browser. Deliberately not a foreign key target for placements.</summary>
    public Guid OperationId { get; set; }

    public long TagId { get; set; }

    /// <summary>See <see cref="EmoteTagOperationKind"/>.</summary>
    public string Kind { get; set; } = string.Empty;

    /// <summary>The set id frozen at registration (a 26-character ULID in practice; the column allows 32).</summary>
    public string SevenTvEmoteSetId { get; set; } = string.Empty;

    public DateTime RegisteredAtUtc { get; set; }

    /// <summary>Null until the report was applied.</summary>
    public DateTime? AppliedAtUtc { get; set; }

    public EmoteTag Tag { get; set; } = null!;
}
